# Site settings
name: Advanced Driver Assist Team
tag_text: autonomous, ADAS, hybrid, computer vision, machine learning, artificial intelligence
description: Innovate the future of autonomous vehicles

# Build settings
markdown: rdiscount
highlighter: pygments

exclude: ["INSTALL.md"]
