# Site settings
name: Advanced Driver Assist Team
tag_text:
description: Innovate the future of autonomous vehicles

# Build settings
markdown: rdiscount
highlighter: pygments

exclude: ["INSTALL.md"]
